export const services = [
  { value: "Netflix", label: "Netflix" },
  { value: "Amazon", label: "Amazon" },
  { value: "Spotify", label: "Spotify" },
  { value: "YouTube Premium", label: "YouTube Premium" },
  { value: "Apple Music", label: "Apple Music" },
  { value: "Coursera", label: "Coursera" },
  { value: "Udemy", label: "Udemy" },
  { value: "SaaS", label: "SaaS" },
  { value: "AWS", label: "AWS" },
  { value: "Azure", label: "Azure" },
  { value: "Google Cloud", label: "Google Cloud" },
  { value: "Microsoft 365", label: "Microsoft 365" },
  { value: "GitHub", label: "GitHub" },
  { value: "Zoom", label: "Zoom" },
  { value: "Canva Pro", label: "Canva Pro" },
  { value: "AliExpress", label: "AliExpress" },
  { value: "Shein", label: "Shein" },
  { value: "Temu", label: "Temu" },
  { value: "Etsy", label: "Etsy" },
  { value: "Facebook Ads", label: "Facebook Ads" },
  { value: "Google Ads", label: "Google Ads" },
  { value: "Shopify", label: "Shopify" },
  { value: "domain names", label: "domain names" },
  { value: "web hosting", label: "web hosting" },
  { value: "Binance", label: "Binance" },
  { value: "KuCoin", label: "KuCoin" },
  { value: "OKX", label: "OKX" },
  { value: "IELTS", label: "IELTS" },
  { value: "TOEFL", label: "TOEFL" },
  { value: "SATs", label: "SATs" }
];

  // { value: "Others", label: "Others" }