export const services = [
    { value: "Netflix", label: "Netflix" },
    { value: "Spotify", label: "Spotify" },
    { value: "Apple Music", label: "Apple Music" },
    { value: "Youtube Premium", label: "Youtube Premium" },
    { value: "Amazon", label: "Amazon" },
    { value: "AliExpress", label: "AliExpress" },
    { value: "eBay", label: "eBay" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "AWS", label: "AWS" },
    { value: "Domains", label: "Domains" },
    { value: "Udemy", label: "Udemy" },
    { value: "Coursera", label: "Coursera" },
    { value: "LinkedIn Learning", label: "LinkedIn Learning" },
    { value: "Facebook Ads", label: "Facebook Ads" },
    { value: "Google Ads", label: "Google Ads" },
    { value: "Instagram Ads", label: "Instagram Ads" },
    { value: "Upwork", label: "Upwork" },
    { value: "Fiverr", label: "Fiverr" },
    { value: "Freelancer", label: "Freelancer" },
    { value: "Xbox", label: "Xbox" },
    { value: "Steam", label: "Steam" },
    { value: "Epic Games", label: "Epic Games" },
    { value: "Bybit", label: "Bybit" },
    { value: "Binance", label: "Binance" },
    { value: "Others", label: "Others" }
  ];